name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main # Deploy only when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Specify the Node.js version you need

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run tests
        run: |
          cd server
          npm test  # Optional: Skip this step if you don't have tests

      - name: Build project
        run: |
          cd server
          npm run build  # Optional: Include this if you have a build step

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./server

      - name: Start app
        run: |
          cd server
          nohup node app.js &  # This starts the app in the background
